---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hyieq.
--- DateTime: 2021/7/16 10:07
---
local getUniqueId = function(obj)
    obj = obj or {}
    return tonumber(tostring(obj):match(':%s*[0xX]*(%x+)'), 16)
end

local EventObj = class('EventObj')

function EventObj:ctor(name, callback, priority)
    self.name = name
    self.callback = callback
    self.priority = priority
    self.id = getUniqueId(self)
    self:bindHost(self)
end

function EventObj:isHostExist()
    return instanceExist(self._host)
end

function EventObj:bindHost(host)
    self._host = host
    return self
end

local EventMediator = class("EventMediator")

function EventMediator.inject(obj, mediator)
    mediator = mediator or EventMediator.new()
    function obj:listen(name, fn, priority)
        if type(obj) == 'userdata' then
            return mediator:listen(name, fn, priority):bindHost(obj)
        else
            return mediator:listen(name, fn, priority)
        end
    end

    function obj:publish(name, ...)
        mediator:publish(name, obj, ...)
    end

    function obj:removeListener(listener)
        mediator:removeListener(listener)
    end

    function obj:removeAllListeners()
        mediator:removeAllListeners()
    end
end

function EventMediator:ctor()
    self._priorityCache = {}
    self._events = {}
end

function EventMediator:listen(name, callback, priority)
    if type(name) == 'string' and string.len(name) > 0 then
        callback = type(callback) == 'function' and callback
        priority = priority or self:_pushPriority(name)
        local event = EventObj.new(name, callback, priority)
        self._events[event.id] = event
        return event
    end
end

function EventMediator:publish(name, ...)
    local events = self:_filterEvents(name)
    events = self:_sortEvents(events)
    for _, event in pairs(events) do
        if event:isHostExist() then
            doCallback(event.callback, ...)
        end
    end
end

function EventMediator:removeListener(listener)
    if not listener or not listener.id then
        return
    end
    self._events[listener.id] = nil
end

function EventMediator:removeAllListeners()
    self._events = {}
    self._priorityCache = {}
end

function EventMediator:_pushPriority(name)
    local p = self._priorityCache[name] or 0
    self._priorityCache[name] = p + 1
    return self._priorityCache[name]
end

function EventMediator:_filterEvents(name)
    local events = {}
    for _, event in pairs(self._events) do
        if event.name == name then
            table.insert(events, event)
        end
        if not event:isHostExist() then
            self._events[event.id] = nil
        end
    end
    return events
end

function EventMediator:_sortEvents(events)
    table.sort(events, function(a, b)
        return a.priority < b.priority
    end)
    return events
end

return EventMediator